const data = [
  {
    id: 1,
    name: "Agra",
    region: "North",
    emoji: "🕌",
    moodTags: ["Relaxing", "Spiritual"],
    purposeTags: ["Family outing", "Weekend escape"],
    themeTags: ["Historical Place", "Family-friendly", "Budget Travel"],
    info: "Agra is a city in northern India, known for the iconic Taj Mahal...",
    image: "https://cdn.thecodehelp.in/Agra.jpeg",
    price: "35,758",
    mapUrl: "https://www.google.com/maps?q=Agra,India&output=embed",
    bestSeason: "October – March",
    specialty: "Mughlai cuisine, Marble handicrafts",
    attraction: "Taj Mahal & Agra Fort",
  },
  {
    id: 2,
    name: "Jaipur",
    region: "North",
    emoji: "🏰",
    moodTags: ["Cultural", "Relaxing"],
    purposeTags: ["Family outing", "Weekend escape"],
    themeTags: ["Historical Place", "Family-friendly"],
    info: "Jaipur is the capital city of the Indian state of Rajasthan...",
    image: "https://cdn.thecodehelp.in/Jaipur.jpeg",
    price: "82,560",
    mapUrl: "https://www.google.com/maps?q=Jaipur,India&output=embed",
    bestSeason: "October – March",
    specialty: "Handicrafts, Ghewar sweet",
    attraction: "Hawa Mahal & Amber Fort",
  },
  {
    id: 3,
    name: "Goa",
    region: "West",
    emoji: "🏖️",
    moodTags: ["Party", "Relaxing"],
    purposeTags: ["Weekend escape", "Solo detox"],
    themeTags: ["Adventure Trip", "Solo Travel", "Budget Travel"],
    info: "Goa is a small state on India's western coast...",
    image: "https://cdn.thecodehelp.in/Goa.jpeg",
    price: "29,695",
    mapUrl: "https://www.google.com/maps?q=Goa,India&output=embed",
    bestSeason: "November – February",
    specialty: "Seafood, Cashew feni",
    attraction: "Baga Beach & Dudhsagar Falls",
  },
  {
    id: 4,
    name: "Varanasi",
    region: "North",
    emoji: "🕉️",
    moodTags: ["Spiritual", "Cultural"],
    purposeTags: ["Solo detox", "Spiritual journey"],
    themeTags: ["Spiritual Trip", "Solo Travel"],
    info: "Varanasi is a holy city in northern India...",
    image: "https://cdn.thecodehelp.in/Varanasi.jpeg",
    price: "31,095",
    mapUrl: "https://www.google.com/maps?q=Varanasi,India&output=embed",
    bestSeason: "October – March",
    specialty: "Banarasi silk sarees, Street food (Kachori Sabzi)",
    attraction: "Kashi Vishwanath Temple & Ganga Aarti at Dashashwamedh Ghat",
  },
  {
    id: 5,
    name: "Darjeeling",
    region: "East",
    emoji: "🏞️",
    moodTags: ["Relaxing", "Nature"],
    purposeTags: ["Nature walk", "Weekend escape"],
    themeTags: ["Adventure Trip", "Family-friendly"],
    info: "Darjeeling is a beautiful hill station...",
    image: "https://cdn.thecodehelp.in/Darjeeling.jpeg",
    price: "78,595",
    mapUrl: "https://www.google.com/maps?q=Darjeeling,India&output=embed",
    bestSeason: "March – May & September – November",
    specialty: "Darjeeling Tea, Momos",
    attraction: "Tiger Hill & Himalayan Railway",
  },
  {
    id: 6,
    name: "Jaisalmer",
    region: "North",
    emoji: "🏜️",
    moodTags: ["Adventurous", "Cultural"],
    purposeTags: ["Nature walk", "Family outing"],
    themeTags: ["Adventure Trip", "Historical Place"],
    info: "Jaisalmer is known for its sandstone architecture...",
    image: "https://cdn.thecodehelp.in/Jaisalmer.jpeg",
    price: "68,595",
    mapUrl: "https://www.google.com/maps?q=Jaisalmer,India&output=embed",
    bestSeason: "October – March",
    specialty: "Rajasthani folk music & embroidery",
    attraction: "Jaisalmer Fort & Desert Safari",
  },
  {
    id: 7,
    name: "Udaipur",
    region: "North",
    emoji: "🏞️",
    moodTags: ["Romantic", "Relaxing"],
    purposeTags: ["Family outing", "Weekend escape"],
    themeTags: ["Historical Place", "Family-friendly"],
    info: "Udaipur is known as the City of Lakes...",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Udaipur_5.jpg",
    price: "22,000",
    mapUrl: "https://www.google.com/maps?q=Udaipur,India&output=embed",
    bestSeason: "September – March",
    specialty: "Miniature paintings, Dal Baati Churma",
    attraction: "City Palace & Lake Pichola",
  },
  {
    id: 8,
    name: "Rishikesh",
    region: "North",
    emoji: "🧘",
    moodTags: ["Spiritual", "Adventurous"],
    purposeTags: ["Solo detox", "Spiritual journey"],
    themeTags: ["Spiritual Trip", "Adventure Trip", "Solo Travel"],
    info: "Rishikesh is the Yoga capital of the world...",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Rishikesh_India_%28183707211%29.jpeg",
    price: "10,000",
    mapUrl: "https://www.google.com/maps?q=Rishikesh,India&output=embed",
    bestSeason: "September – November & March – May",
    specialty: "Yoga retreats, Ayurvedic food",
    attraction: "Laxman Jhula & River Rafting",
  },
  {
    id: 9,
    name: "Khajuraho",
    region: "North",
    emoji: "🛕",
    moodTags: ["Cultural", "Romantic"],
    purposeTags: ["Spiritual journey", "Couple trip"],
    themeTags: ["Historical Place", "Spiritual Trip"],
    info: "Famous for its UNESCO-listed group of temples...",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Khajuraho_Dulhadeo_2010.jpg",
    price: "16,500",
    mapUrl: "https://www.google.com/maps?q=Khajuraho,India&output=embed",
    bestSeason: "October – March",
    specialty: "Classical dance festival, Stone carvings",
    attraction: "Kandariya Mahadev Temple",
  },
  {
    id: 10,
    name: "Munnar",
    region: "South",
    emoji: "🍃",
    moodTags: ["Relaxing", "Nature"],
    purposeTags: ["Nature walk", "Solo detox"],
    themeTags: ["Adventure Trip", "Solo Travel"],
    info: "A beautiful hill station in Kerala...",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Munnar_-_View_from_Grand_Plaza_Hotel.jpg",
    price: "18,500",
    mapUrl: "https://www.google.com/maps?q=Munnar,India&output=embed",
    bestSeason: "September – May",
    specialty: "Tea plantations, Spices",
    attraction: "Eravikulam National Park",
  },
  {
    id: 11,
    name: "Amritsar",
    region: "North",
    emoji: "🕍",
    moodTags: ["Spiritual", "Cultural"],
    purposeTags: ["Family outing", "Spiritual journey"],
    themeTags: ["Spiritual Trip", "Historical Place", "Educational Tour"],
    info: "Home to the Golden Temple, the holiest shrine of Sikhism...",
    image: "/images/Amritsar.jpg",
    price: "14,000",
    mapUrl: "https://www.google.com/maps?q=Amritsar,India&output=embed",
    bestSeason: "October – March",
    specialty: "Amritsari Kulcha, Phulkari embroidery",
    attraction: "Golden Temple & Wagah Border",
  },
  {
    id: 12,
    name: "Hampi",
    region: "South",
    emoji: "🏛️",
    moodTags: ["Adventurous", "Cultural"],
    purposeTags: ["Solo detox", "History tour"],
    themeTags: ["Historical Place", "Solo Travel", "Educational Tour"],
    info: "An ancient village famous for its ruins...",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Hampi%2C_India%2C_Stone_ornaments_at_Vijaya_Vitthala_Temple.jpg",
    price: "17,000",
    mapUrl: "https://www.google.com/maps?q=Hampi,India&output=embed",
    bestSeason: "October – February",
    specialty: "Stone carvings, Banana fritters",
    attraction: "Vittala Temple & Virupaksha Temple",
  },
];

export default data;
