const data = [
  {
    id: 1,
    name: "Agra",
    region: "North",
    emoji: "🕌",
    moodTags: ["Relaxing", "Spiritual"],
    purposeTags: ["Family outing", "Weekend escape"],
    info: "Agra is a city in northern India, known for the iconic Taj Mahal...",
    image: "https://cdn.thecodehelp.in/Agra.jpeg",
    price: "35,758",
  },
  {
    id: 2,
    name: "Jaipur",
    region: "North",
    emoji: "🏰",
    moodTags: ["Cultural", "Relaxing"],
    purposeTags: ["Family outing", "Weekend escape"],
    info: "Jaipur is the capital city of the Indian state of Rajasthan...",
    image: "https://cdn.thecodehelp.in/Jaipur.jpeg",
    price: "82,560",
  },
  {
    id: 3,
    name: "Goa",
    region: "West",
    emoji: "🏖️",
    moodTags: ["Party", "Relaxing"],
    purposeTags: ["Weekend escape", "Solo detox"],
    info: "Goa is a small state on India's western coast...",
    image: "https://cdn.thecodehelp.in/Goa.jpeg",
    price: "29,695",
  },
  {
    id: 4,
    name: "Varanasi",
    region: "North",
    emoji: "🕉️",
    moodTags: ["Spiritual", "Cultural"],
    purposeTags: ["Solo detox", "Spiritual journey"],
    info: "Varanasi is a holy city in northern India...",
    image: "https://cdn.thecodehelp.in/Varanasi.jpeg",
    price: "31,095",
  },
  {
    id: 5,
    name: "Darjeeling",
    region: "East",
    emoji: "🏞️",
    moodTags: ["Relaxing", "Nature"],
    purposeTags: ["Nature walk", "Weekend escape"],
    info: "Darjeeling is a beautiful hill station...",
    image: "https://cdn.thecodehelp.in/Darjeeling.jpeg",
    price: "78,595",
  },
  {
    id: 6,
    name: "Jaisalmer",
    region: "North",
    emoji: "🏜️",
    moodTags: ["Adventurous", "Cultural"],
    purposeTags: ["Nature walk", "Family outing"],
    info: "Jaisalmer is known for its sandstone architecture...",
    image: "https://cdn.thecodehelp.in/Jaisalmer.jpeg",
    price: "68,595",
  },
  {
    id: 7,
    name: "Udaipur",
    region: "North",
    emoji: "🏞️",
    moodTags: ["Romantic", "Relaxing"],
    purposeTags: ["Family outing", "Weekend escape"],
    info: "Udaipur is known as the City of Lakes...",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Udaipur_5.jpg",
    price: "22,000",
  },
  {
    id: 8,
    name: "Rishikesh",
    region: "North",
    emoji: "🧘",
    moodTags: ["Spiritual", "Adventurous"],
    purposeTags: ["Solo detox", "Spiritual journey"],
    info: "Rishikesh is the Yoga capital of the world...",
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Rishikesh_India_%28183707211%29.jpeg",
    price: "10,000",
  },
  {
    id: 9,
    name: "Khajuraho",
    region: "North",
    emoji: "🛕",
    moodTags: ["Cultural", "Romantic"],
    purposeTags: ["Spiritual journey", "Couple trip"],
    info: "Famous for its UNESCO-listed group of temples...",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Khajuraho_Dulhadeo_2010.jpg",
    price: "16,500",
  },
  {
    id: 10,
    name: "Munnar",
    region: "South",
    emoji: "🍃",
    moodTags: ["Relaxing", "Nature"],
    purposeTags: ["Nature walk", "Solo detox"],
    info: "A beautiful hill station in Kerala...",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Munnar_-_View_from_Grand_Plaza_Hotel.jpg",
    price: "18,500",
  },
  {
    id: 11,
    name: "Amritsar",
    region: "North",
    emoji: "🕍",
    moodTags: ["Spiritual", "Cultural"],
    purposeTags: ["Family outing", "Spiritual journey"],
    info: "Home to the Golden Temple, the holiest shrine of Sikhism...",
    image: "/images/Amritsar.jpg",
    price: "14,000",
  },
  {
    id: 12,
    name: "Hampi",
    region: "South",
    emoji: "🏛️",
    moodTags: ["Adventurous", "Cultural"],
    purposeTags: ["Solo detox", "History tour"],
    info: "An ancient village famous for its ruins...",
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f2/Hampi%2C_India%2C_Stone_ornaments_at_Vijaya_Vitthala_Temple.jpg",
    price: "17,000",
  },
];

export default data;
